"""
Structured Product Evaluation Service for Simulation Explorer.

Evaluates structured products on existing MC paths generated by run_simulation(),
reusing the same Numba kernels as StructuredProductMCEngine but without re-simulating.

Author: Thomas Vaudescal
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from backend.core.market import MarketEnvironment
from backend.engines.structured_mc_engine import StructuredProductMCEngine
from backend.instruments.structured.products import (
    Autocallable,
    CapitalProtectedNote,
    PhoenixAutocallable,
    ReverseConvertible,
    SharkNote,
    SnowballAutocallable,
    TwinWin,
)


# ─────────────────────────────────────────────────────────────────────
# Result dataclass
# ─────────────────────────────────────────────────────────────────────


@dataclass
class StructuredSimulationResult:
    """Result of evaluating a structured product on simulation paths."""

    per_path_pv: np.ndarray  # (n_paths,)
    per_path_returns: np.ndarray  # (n_paths,)
    bond_floor_pv: np.ndarray  # (n_paths,)
    option_pv: np.ndarray  # (n_paths,)
    coupon_pv: np.ndarray  # (n_paths,)
    autocall_called: np.ndarray  # (n_paths,) bool
    barrier_breached: np.ndarray  # (n_paths,) bool
    pricing_summary: dict = field(default_factory=dict)
    observation_times: np.ndarray = field(default_factory=lambda: np.array([]))
    observation_indices: np.ndarray = field(
        default_factory=lambda: np.array([], dtype=int)
    )
    product_type: str = ""
    product_config: dict = field(default_factory=dict)
    autocall_date_index: np.ndarray = field(
        default_factory=lambda: np.array([], dtype=int)
    )


# ─────────────────────────────────────────────────────────────────────
# Factory helper (reuse from options_greeks adapter)
# ─────────────────────────────────────────────────────────────────────


def _build_product(product_type: str, params: dict):
    """Instantiate a StructuredProduct from config dict."""
    if product_type == "cpn":
        return CapitalProtectedNote(
            notional_=params["notional"],
            maturity_=params["maturity"],
            participation_rate=params["participation_rate"],
            cap=params.get("cap"),
            observation_frequency=params["observation_frequency"],
            protection_level=params.get("protection_level", 1.0),
        )
    if product_type == "reverse_convertible":
        return ReverseConvertible(
            notional_=params["notional"],
            maturity_=params["maturity"],
            coupon_rate=params["coupon_rate"],
            barrier=params["barrier"],
            barrier_monitoring=params.get("barrier_monitoring", "continuous"),
            observation_frequency=params["observation_frequency"],
        )
    if product_type == "autocallable":
        return Autocallable(
            notional_=params["notional"],
            maturity_=params["maturity"],
            coupon_rate=params["coupon_rate"],
            autocall_trigger=params["autocall_trigger"],
            coupon_barrier=params["coupon_barrier"],
            ki_barrier=params["ki_barrier"],
            memory_coupon=params.get("memory_coupon", True),
            barrier_monitoring=params.get("barrier_monitoring", "continuous"),
            observation_frequency=params["observation_frequency"],
        )
    if product_type == "phoenix":
        return PhoenixAutocallable(
            notional_=params["notional"],
            maturity_=params["maturity"],
            coupon_rate=params["coupon_rate"],
            autocall_trigger=params["autocall_trigger"],
            coupon_barrier=params["coupon_barrier"],
            ki_barrier=params["ki_barrier"],
            memory_coupon=params.get("memory_coupon", True),
            barrier_monitoring=params.get("barrier_monitoring", "continuous"),
            observation_frequency=params["observation_frequency"],
        )
    if product_type == "shark_note":
        return SharkNote(
            notional_=params["notional"],
            maturity_=params["maturity"],
            participation_rate=params.get("participation_rate", 1.50),
            ko_barrier=params.get("ko_barrier", 1.40),
            rebate=params.get("rebate", 0.05),
            protection_level=params.get("protection_level", 1.0),
            observation_frequency=params["observation_frequency"],
        )
    if product_type == "twin_win":
        return TwinWin(
            notional_=params["notional"],
            maturity_=params["maturity"],
            participation_rate=params.get("participation_rate", 1.0),
            ki_barrier=params.get("ki_barrier", 0.60),
            barrier_monitoring=params.get("barrier_monitoring", "continuous"),
            observation_frequency=params["observation_frequency"],
        )
    if product_type == "snowball":
        return SnowballAutocallable(
            notional_=params["notional"],
            maturity_=params["maturity"],
            coupon_rate=params["coupon_rate"],
            autocall_trigger=params.get("autocall_trigger", 1.0),
            ki_barrier=params.get("ki_barrier", 0.60),
            barrier_monitoring=params.get("barrier_monitoring", "continuous"),
            observation_frequency=params["observation_frequency"],
        )
    raise ValueError(f"Unknown product type: {product_type}")


# ─────────────────────────────────────────────────────────────────────
# Main evaluation function
# ─────────────────────────────────────────────────────────────────────


def evaluate_structured_product_on_paths(
    sim_result,
    product_config: dict,
    market_params: dict,
) -> StructuredSimulationResult:
    """
    Evaluate a structured product on pre-existing simulation paths.

    Parameters
    ----------
    sim_result : SimulationResult
        Result from run_simulation() with price_paths and time_grid.
    product_config : dict
        Product configuration from the sidebar builder.
        Keys: product_type, product_params, notional, maturity.
    market_params : dict
        Market parameters (spot, risk_free_rate, etc.).

    Returns
    -------
    StructuredSimulationResult
    """
    product_type = product_config["product_type"]
    product_params = product_config["product_params"]

    # Build the product
    product = _build_product(product_type, product_params)

    # Get paths and time grid from simulation
    paths = sim_result.price_paths  # (n_paths, n_steps+1)
    time_grid = sim_result.time_grid  # (n_steps+1,)
    n_paths = paths.shape[0]

    # Map observation schedule to time grid indices
    schedule = product.observation_schedule
    obs_indices = StructuredProductMCEngine._map_obs_to_grid(schedule, time_grid)

    # Compute discount factors
    rate = market_params.get("risk_free_rate", 0.05)
    obs_times = time_grid[obs_indices]
    discount_factors = np.exp(-rate * obs_times)

    # Period lengths
    prev_times = np.concatenate([[0.0], obs_times[:-1]])
    obs_dt = obs_times - prev_times

    # Terminal discount factor
    maturity = product_params["maturity"]
    df_terminal = float(np.exp(-rate * maturity))

    # Reference spot = initial spot from params (consistent across all paths)
    s0 = market_params.get("spot", paths[0, 0])

    # Evaluate product on paths (polymorphic dispatch with generic fallback)
    components = product.evaluate_paths(
        paths,
        obs_indices,
        discount_factors,
        obs_dt,
        df_terminal,
        s0_reference=s0,
    )

    if components is None:
        # Use generic evaluator for products without custom kernel
        engine = StructuredProductMCEngine()
        components = engine._price_generic(
            product,
            paths,
            time_grid,
            obs_indices,
            discount_factors,
            obs_dt,
            df_terminal,
            s0_reference=s0,
        )

    per_path_pv = components["pv"]
    bond_floor_pv = components["bond_floor_pv"]
    option_pv = components["option_pv"]
    coupon_pv = components["coupon_pv"]
    autocall_prob = components["autocall_probability"]

    # Compute returns
    notional = product_params["notional"]
    per_path_returns = per_path_pv / notional - 1.0

    # Post-processing: detect barrier breaches and autocall dates
    barrier_breached = _detect_barrier_breaches(
        paths,
        product_type,
        product_params,
        s0,
        obs_indices,
    )
    autocall_called, autocall_date_idx = _detect_autocall_dates(
        paths,
        product_type,
        product_params,
        s0,
        obs_indices,
    )

    # Build pricing summary
    mean_pv = float(np.mean(per_path_pv))  # pyright: ignore[reportCallIssue]
    std_err = float(np.std(per_path_pv) / np.sqrt(n_paths))  # pyright: ignore[reportCallIssue]
    fair_value = mean_pv / notional * 100

    pricing_summary = {
        "fair_value": fair_value,
        "price": mean_pv,
        "error": std_err,
        "notional": notional,
        "expected_return": float(np.mean(per_path_returns)),  # pyright: ignore[reportCallIssue]
        "std_return": float(np.std(per_path_returns)),  # pyright: ignore[reportCallIssue]
        "worst_case_return": float(np.percentile(per_path_returns, 5)),
        "best_case_return": float(np.percentile(per_path_returns, 95)),
        "prob_profit": float(np.mean(per_path_returns >= 0)),  # pyright: ignore[reportCallIssue]
        "prob_capital_loss": float(np.mean(per_path_pv < notional)),
        "autocall_probability": autocall_prob
        if product_type in ("autocallable", "phoenix", "snowball")
        else None,
        "barrier_breach_probability": float(np.mean(barrier_breached)),
        "decomposition": {
            "bond_floor": float(np.mean(bond_floor_pv)) / notional * 100,  # pyright: ignore[reportCallIssue]
            "option_value": float(np.mean(option_pv)) / notional * 100,  # pyright: ignore[reportCallIssue]
            "coupon_pv": float(np.mean(coupon_pv)) / notional * 100,  # pyright: ignore[reportCallIssue]
        },
    }

    return StructuredSimulationResult(
        per_path_pv=per_path_pv,
        per_path_returns=per_path_returns,
        bond_floor_pv=bond_floor_pv,
        option_pv=option_pv,
        coupon_pv=coupon_pv,
        autocall_called=autocall_called,
        barrier_breached=barrier_breached,
        pricing_summary=pricing_summary,
        observation_times=obs_times,
        observation_indices=obs_indices,
        product_type=product_type,
        product_config=product_config,
        autocall_date_index=autocall_date_idx,
    )


# ─────────────────────────────────────────────────────────────────────
# Event detection helpers
# ─────────────────────────────────────────────────────────────────────


def _detect_barrier_breaches(
    paths: np.ndarray,
    product_type: str,
    product_params: dict,
    s0: float,
    obs_indices: np.ndarray,
) -> np.ndarray:
    """Detect which paths breach the barrier and return boolean array."""
    n_paths = paths.shape[0]

    if product_type in ("cpn", "shark_note"):
        return np.zeros(n_paths, dtype=bool)

    if product_type == "reverse_convertible":
        barrier_level = product_params["barrier"] * s0
        monitoring = product_params.get("barrier_monitoring", "continuous")
    elif product_type in ("autocallable", "phoenix", "snowball", "twin_win"):
        barrier_level = product_params["ki_barrier"] * s0
        monitoring = product_params.get("barrier_monitoring", "continuous")
    else:
        return np.zeros(n_paths, dtype=bool)

    breached = np.zeros(n_paths, dtype=bool)
    if monitoring == "continuous":
        # Check all steps
        breached = np.any(paths <= barrier_level, axis=1)
    else:
        # Check only observation dates
        for j in range(len(obs_indices)):
            breached |= paths[:, obs_indices[j]] <= barrier_level

    return breached


def _detect_autocall_dates(
    paths: np.ndarray,
    product_type: str,
    product_params: dict,
    s0: float,
    obs_indices: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Detect autocall events per path.

    Returns
    -------
    called : np.ndarray (n_paths,) bool
    autocall_date_index : np.ndarray (n_paths,) int
        Index into obs_indices where autocall occurred (-1 if not called).
    """
    n_paths = paths.shape[0]
    called = np.zeros(n_paths, dtype=bool)
    autocall_date_idx = np.full(n_paths, -1, dtype=int)

    if product_type not in ("autocallable", "phoenix", "snowball"):
        return called, autocall_date_idx

    trigger = product_params["autocall_trigger"]
    trigger_level = trigger * s0

    for j in range(len(obs_indices)):
        idx = obs_indices[j]
        spot_at_obs = paths[:, idx]
        newly_called = (~called) & (spot_at_obs >= trigger_level)
        autocall_date_idx[newly_called] = j
        called |= newly_called

    return called, autocall_date_idx


# ─────────────────────────────────────────────────────────────────────
# Scenario analysis (delegates to StructuredProductMCEngine)
# ─────────────────────────────────────────────────────────────────────


def compute_structured_scenario_analysis(
    product_config: dict,
    market_params: dict,
    n_scenarios: int = 30,
    n_paths: int = 10_000,
    seed: int | None = 42,
) -> dict:
    """
    Price the product across a range of spot prices for scenario chart.

    Returns dict with keys: spots, fair_values, prices, deltas.
    """
    from backend.models.gbm import GBMModel
    from backend.models.heston import HestonModel

    product_type = product_config["product_type"]
    product_params = product_config["product_params"]
    product = _build_product(product_type, product_params)

    spot = market_params.get("spot", 100.0)
    rate = market_params.get("risk_free_rate", 0.05)
    sigma = market_params.get("sigma", 0.20)

    # Build model based on what's available
    model_key = market_params.get("model", "gbm")
    if model_key == "heston":
        model = HestonModel(
            v0=market_params.get("v0", 0.04),
            kappa=market_params.get("kappa", 2.0),
            theta=market_params.get("theta", 0.04),
            alpha=market_params.get("alpha", 0.3),
            rho=market_params.get("rho", -0.7),
        )
    else:
        model = GBMModel(sigma=sigma)

    market = MarketEnvironment(spot=spot, rate=rate)
    spot_range = np.linspace(spot * 0.6, spot * 1.4, n_scenarios)

    engine = StructuredProductMCEngine(n_paths=n_paths, seed=seed)
    result = engine.scenario_analysis(product, model, market, spot_range)

    return {
        "spots": result["spots"],
        "fair_values": result["fair_values"],
        "prices": result["prices"],
        "deltas": result["deltas"],
    }
