"""
Heston path-simulation Numba kernels (one per discretization scheme)
====================================================================

Split out of ``heston.py``: the former single kernel carried a per-step
``if scheme == ...`` chain over all four variance discretizations and a
uniform signature that forced dummy QE buffers onto the non-QE schemes.
Each scheme now compiles to its own specialized kernel — the scheme
branch leaves the hot loop, the non-QE kernels drop the two unused
``(n_paths, n_steps)`` buffers, and the QE kernel hoists its
``kappa``/``dt``-only subexpressions out of the step loop.

All random draws are pre-generated by the caller and passed via the
``z1_noise``/``z2_noise`` (and, for QE, ``qe_normal``/``qe_uniform``)
arrays. This makes the parallel kernels deterministic across runs for a
fixed seed and avoids Numba's thread-local RNG race conditions.

Author: Thomas Vaudescal
Created: 2026
"""

from __future__ import annotations

import numpy as np
from numba import njit, prange

from backend.utils.constants.numerical import QE_M_FLOOR, QE_PSI_THRESHOLD

# Module-level aliases captured by Numba at compile time.
_M_FLOOR = QE_M_FLOOR
_QE_PSI_THRESHOLD = QE_PSI_THRESHOLD


@njit(parallel=True, cache=True, fastmath=True)
def heston_paths_euler(
    s0: float,
    v0: float,
    mu: float,
    kappa: float,
    theta: float,
    alpha: float,
    rho: float,
    t: float,
    n_paths: int,
    n_steps: int,
    z1_noise: np.ndarray,
    z2_noise: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Simple Euler scheme (variance can go negative)."""
    dt = t / n_steps
    sqrt_dt = np.sqrt(dt)
    sqrt_one_minus_rho2 = np.sqrt(1.0 - rho * rho)

    s_paths = np.empty((n_paths, n_steps + 1), dtype=np.float64)
    v_paths = np.empty((n_paths, n_steps + 1), dtype=np.float64)

    for i in prange(n_paths):
        s_paths[i, 0] = s0
        v_paths[i, 0] = v0

        for j in range(n_steps):
            z1 = z1_noise[i, j]
            z2 = z2_noise[i, j]

            dw_s = sqrt_dt * z1
            dw_v = sqrt_dt * (rho * z1 + sqrt_one_minus_rho2 * z2)

            v_curr = v_paths[i, j]
            s_curr = s_paths[i, j]

            sqrt_v = np.sqrt(max(v_curr, 0.0))
            v_next = v_curr + kappa * (theta - v_curr) * dt + alpha * sqrt_v * dw_v
            s_next = s_curr * np.exp((mu - 0.5 * v_curr) * dt + sqrt_v * dw_s)

            v_paths[i, j + 1] = v_next
            s_paths[i, j + 1] = s_next

    return s_paths, v_paths


@njit(parallel=True, cache=True, fastmath=True)
def heston_paths_full_truncation(
    s0: float,
    v0: float,
    mu: float,
    kappa: float,
    theta: float,
    alpha: float,
    rho: float,
    t: float,
    n_paths: int,
    n_steps: int,
    z1_noise: np.ndarray,
    z2_noise: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Full-truncation scheme (variance floored at 0 in drift and diffusion)."""
    dt = t / n_steps
    sqrt_dt = np.sqrt(dt)
    sqrt_one_minus_rho2 = np.sqrt(1.0 - rho * rho)

    s_paths = np.empty((n_paths, n_steps + 1), dtype=np.float64)
    v_paths = np.empty((n_paths, n_steps + 1), dtype=np.float64)

    for i in prange(n_paths):
        s_paths[i, 0] = s0
        v_paths[i, 0] = v0

        for j in range(n_steps):
            z1 = z1_noise[i, j]
            z2 = z2_noise[i, j]

            dw_s = sqrt_dt * z1
            dw_v = sqrt_dt * (rho * z1 + sqrt_one_minus_rho2 * z2)

            v_curr = v_paths[i, j]
            s_curr = s_paths[i, j]

            v_plus = max(v_curr, 0.0)
            sqrt_v = np.sqrt(v_plus)
            v_next = v_curr + kappa * (theta - v_plus) * dt + alpha * sqrt_v * dw_v
            v_next = max(v_next, 0.0)
            s_next = s_curr * np.exp((mu - 0.5 * v_plus) * dt + sqrt_v * dw_s)

            v_paths[i, j + 1] = v_next
            s_paths[i, j + 1] = s_next

    return s_paths, v_paths


@njit(parallel=True, cache=True, fastmath=True)
def heston_paths_reflection(
    s0: float,
    v0: float,
    mu: float,
    kappa: float,
    theta: float,
    alpha: float,
    rho: float,
    t: float,
    n_paths: int,
    n_steps: int,
    z1_noise: np.ndarray,
    z2_noise: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Reflection scheme (negative variance reflected to its absolute value)."""
    dt = t / n_steps
    sqrt_dt = np.sqrt(dt)
    sqrt_one_minus_rho2 = np.sqrt(1.0 - rho * rho)

    s_paths = np.empty((n_paths, n_steps + 1), dtype=np.float64)
    v_paths = np.empty((n_paths, n_steps + 1), dtype=np.float64)

    for i in prange(n_paths):
        s_paths[i, 0] = s0
        v_paths[i, 0] = v0

        for j in range(n_steps):
            z1 = z1_noise[i, j]
            z2 = z2_noise[i, j]

            dw_s = sqrt_dt * z1
            dw_v = sqrt_dt * (rho * z1 + sqrt_one_minus_rho2 * z2)

            v_curr = v_paths[i, j]
            s_curr = s_paths[i, j]

            v_plus = abs(v_curr)
            sqrt_v = np.sqrt(v_plus)
            v_next = v_curr + kappa * (theta - v_plus) * dt + alpha * sqrt_v * dw_v
            v_next = abs(v_next)
            s_next = s_curr * np.exp((mu - 0.5 * v_plus) * dt + sqrt_v * dw_s)

            v_paths[i, j + 1] = v_next
            s_paths[i, j + 1] = s_next

    return s_paths, v_paths


@njit(parallel=True, cache=True, fastmath=True)
def heston_paths_qe(
    s0: float,
    v0: float,
    mu: float,
    kappa: float,
    theta: float,
    alpha: float,
    rho: float,
    t: float,
    n_paths: int,
    n_steps: int,
    z1_noise: np.ndarray,
    z2_noise: np.ndarray,  # kept for draw-layout compatibility (see note)
    qe_normal: np.ndarray,
    qe_uniform: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Andersen (2008) Quadratic Exponential scheme.

    The variance update uses ``qe_normal``/``qe_uniform``; the log-asset update
    uses ``z1_noise`` as the asset's independent Gaussian and couples to the
    realized variance via the K0..K4 coefficients (this is what carries the
    rho leverage — see the step body). ``z2_noise`` stays in the signature so
    the caller's seeded draw layout (z1, z2, qe_normal, qe_uniform), and hence
    every path for a fixed seed, is unchanged.
    """
    dt = t / n_steps
    sqrt_dt = np.sqrt(dt)

    # kappa/dt-only QE subexpressions are loop-invariant: hoisted from the
    # per-step body (the former combined kernel re-evaluated exp(-kappa*dt)
    # at every step of every path).
    exp_kappa_dt = np.exp(-kappa * dt)
    s2_v_coeff = alpha * alpha * exp_kappa_dt / kappa * (1.0 - exp_kappa_dt)
    s2_const = theta * alpha * alpha / (2.0 * kappa) * (1.0 - exp_kappa_dt) ** 2

    # Andersen (2008) QE asset-coupling coefficients (central discretization,
    # gamma1 = gamma2 = 1/2). Loop-invariant in kappa/theta/alpha/rho/dt.
    # These inject the rho leverage into the log-asset step via V_t and V_{t+dt}.
    alpha_safe = alpha if abs(alpha) > 1e-12 else 1e-12
    rho_over_alpha = rho / alpha_safe
    qe_k0 = -rho * kappa * theta * dt / alpha_safe
    _qe_drift = 0.5 * dt * (kappa * rho_over_alpha - 0.5)
    qe_k1 = _qe_drift - rho_over_alpha
    qe_k2 = _qe_drift + rho_over_alpha
    qe_k3 = 0.5 * dt * (1.0 - rho * rho)
    qe_k4 = qe_k3

    s_paths = np.empty((n_paths, n_steps + 1), dtype=np.float64)
    v_paths = np.empty((n_paths, n_steps + 1), dtype=np.float64)

    for i in prange(n_paths):
        s_paths[i, 0] = s0
        v_paths[i, 0] = v0

        for j in range(n_steps):
            v_curr = v_paths[i, j]
            s_curr = s_paths[i, j]

            v_plus = max(v_curr, 0.0)

            # Moment matching: m (mean) and s2 (variance) of V_{t+dt} | V_t
            m = theta + (v_plus - theta) * exp_kappa_dt
            s2 = v_plus * s2_v_coeff + s2_const

            psi = s2 / (m * m) if m > _M_FLOOR else 1000.0

            if psi <= _QE_PSI_THRESHOLD:
                # Moment-matched quadratic approximation
                b2 = 2.0 / psi - 1.0 + np.sqrt(2.0 / psi * (2.0 / psi - 1.0))
                a = m / (1.0 + b2)
                z_v = qe_normal[i, j]
                v_next = a * (np.sqrt(b2) + z_v) ** 2
            else:
                # Exponential approximation
                p = (psi - 1.0) / (psi + 1.0)
                beta = (1.0 - p) / m if m > _M_FLOOR else 1.0
                u = qe_uniform[i, j]
                if u <= p:
                    v_next = 0.0
                else:
                    v_next = np.log((1.0 - p) / (1.0 - u)) / beta

            # Andersen QE log-asset update couples S to the realized variance
            # (V_t and V_{t+dt}) via K0..K4, so the rho leverage is present. The
            # previous step used a plain sqrt(V_t)*sqrt_dt*z1 Euler increment that
            # never referenced rho, leaving corr(dlnS, dV) identically zero and
            # destroying Heston's skew. z1 is the asset's own (independent)
            # Gaussian; the correlation enters through the K1/K2 variance terms.
            z_s = z1_noise[i, j]
            log_step = (
                mu * dt
                + qe_k0
                + qe_k1 * v_plus
                + qe_k2 * v_next
                + np.sqrt(qe_k3 * v_plus + qe_k4 * v_next) * z_s
            )
            s_next = s_curr * np.exp(log_step)

            v_paths[i, j + 1] = v_next
            s_paths[i, j + 1] = s_next

    return s_paths, v_paths


@njit(parallel=True, cache=True, fastmath=True)
def heston_terminal_full_truncation(
    s0: float,
    v0: float,
    mu: float,
    kappa: float,
    theta: float,
    alpha: float,
    rho: float,
    t: float,
    n_paths: int,
    n_steps: int,
    z1_noise: np.ndarray,
    z2_noise: np.ndarray,
) -> np.ndarray:
    """Terminal-only Heston simulation under the full-truncation scheme."""
    dt = t / n_steps
    sqrt_dt = np.sqrt(dt)
    sqrt_one_minus_rho2 = np.sqrt(1.0 - rho * rho)

    terminals = np.empty(n_paths, dtype=np.float64)

    for i in prange(n_paths):
        s = s0
        v = v0

        for j in range(n_steps):
            z1 = z1_noise[i, j]
            z2 = z2_noise[i, j]

            dw_s = sqrt_dt * z1
            dw_v = sqrt_dt * (rho * z1 + sqrt_one_minus_rho2 * z2)

            v_plus = max(v, 0.0)
            sqrt_v = np.sqrt(v_plus)

            v = max(v + kappa * (theta - v_plus) * dt + alpha * sqrt_v * dw_v, 0.0)
            s = s * np.exp((mu - 0.5 * v_plus) * dt + sqrt_v * dw_s)

        terminals[i] = s

    return terminals
