"""
GJR-GARCH Simulator
===================

Implementation of the GJR-GARCH model (Glosten, Jagannathan, Runkle, 1993)
with joint price-volatility dynamics.

Model Specification:
    Return dynamics:
        r_t = (μ - 0.5·σ²_t)·dt + σ_t·√dt·z_t,  where z_t ~ N(0,1)
        S_t = S_{t-1}·exp(r_t)

    Variance dynamics (GJR-GARCH):
        σ²_t = ω + (α + γ·I_{t-1})·σ²_{t-1}·z²_{t-1} + β·σ²_{t-1}

    Where I_{t-1} = 1 if z_{t-1} < 0 (negative return), else 0

The γ parameter captures leverage via an indicator function:
    - γ > 0: Negative returns add extra volatility
    - γ = 0: Reduces to standard GARCH(1,1)

Stationarity condition: α + 0.5·γ + β < 1
Long-run variance: σ²_∞ = ω / (1 - α - 0.5·γ - β)

References:
    Glosten, L.R., Jagannathan, R. and Runkle, D.E. (1993). "On the Relation
    between the Expected Value and the Volatility of the Nominal Excess
    Return on Stocks." Journal of Finance, 48(5), 1779-1801.

Author: Thomas Vaudescal
Created: 2026
"""

from __future__ import annotations

import time
from typing import Any

import numpy as np
from numba import njit, prange

from backend.simulation.base import (
    BaseSimulator,
    SimulationResult,
    StochasticVolatilityMixin,
)
from backend.utils.constants.numerical import GARCH_VARIANCE_FLOOR

# Aliased locally so the kernel reads the centralised value at compile time.
_VARIANCE_FLOOR = GARCH_VARIANCE_FLOOR


# =============================================================================
# Numba-Optimized Kernels
# =============================================================================


@njit(parallel=True, cache=True, fastmath=True)
def _simulate_gjr_garch_paths(
    s0: float,
    mu: float,
    sigma0: float,
    omega: float,
    alpha: float,
    beta: float,
    gamma: float,
    t: float,
    n_paths: int,
    n_steps: int,
    z_noise: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Numba kernel for GJR-GARCH joint price-volatility simulation.

    The indicator I = 1 if z < 0 adds extra volatility response to negative
    shocks. Innovations are pre-generated by the caller in ``z_noise`` to
    guarantee thread-safe reproducibility under ``parallel=True``.
    """
    dt = t / n_steps
    sqrt_dt = np.sqrt(dt)

    var0 = sigma0 * sigma0

    price_paths = np.empty((n_paths, n_steps + 1), dtype=np.float64)
    vol_paths = np.empty((n_paths, n_steps + 1), dtype=np.float64)

    for i in prange(n_paths):
        price_paths[i, 0] = s0
        vol_paths[i, 0] = sigma0

        var_t = var0

        for j in range(n_steps):
            z = z_noise[i, j]

            # Current volatility
            sigma_t = np.sqrt(var_t)
            vol_paths[i, j] = sigma_t

            # Log return with volatility adjustment
            log_return = (mu - 0.5 * var_t) * dt + sigma_t * sqrt_dt * z

            # Price update
            price_paths[i, j + 1] = price_paths[i, j] * np.exp(log_return)

            # GJR-GARCH variance update with indicator
            indicator = 1.0 if z < 0.0 else 0.0
            z_sq = z * z
            var_next = omega + (alpha + gamma * indicator) * var_t * z_sq + beta * var_t
            var_t = max(var_next, _VARIANCE_FLOOR)

        # Store final volatility
        vol_paths[i, n_steps] = np.sqrt(var_t)

    return price_paths, vol_paths


@njit(parallel=True, cache=True, fastmath=True)
def _simulate_gjr_garch_terminal(
    s0: float,
    mu: float,
    sigma0: float,
    omega: float,
    alpha: float,
    beta: float,
    gamma: float,
    t: float,
    n_paths: int,
    n_steps: int,
    z_noise: np.ndarray,
) -> np.ndarray:
    """
    Numba kernel for terminal-only GJR-GARCH simulation. Innovations are
    pre-generated by the caller in ``z_noise``.
    """
    dt = t / n_steps
    sqrt_dt = np.sqrt(dt)

    var0 = sigma0 * sigma0

    terminals = np.empty(n_paths, dtype=np.float64)

    for i in prange(n_paths):
        s = s0
        var_t = var0

        for j in range(n_steps):
            z = z_noise[i, j]

            sigma_t = np.sqrt(var_t)
            log_return = (mu - 0.5 * var_t) * dt + sigma_t * sqrt_dt * z
            s = s * np.exp(log_return)

            indicator = 1.0 if z < 0.0 else 0.0
            z_sq = z * z
            var_next = omega + (alpha + gamma * indicator) * var_t * z_sq + beta * var_t
            var_t = max(var_next, _VARIANCE_FLOOR)

        terminals[i] = s

    return terminals


# =============================================================================
# GJR-GARCH Simulator Class
# =============================================================================


class GJRGARCHSimulator(BaseSimulator, StochasticVolatilityMixin):
    """
    GJR-GARCH model simulator with leverage effect.

    The variance follows the GJR-GARCH recursion:
        σ²_t = ω + (α + γ·I_{t-1})·σ²_{t-1}·z²_{t-1} + β·σ²_{t-1}

    Where I_{t-1} = 1 if z_{t-1} < 0 (negative return indicator).

    The γ parameter introduces asymmetry (leverage effect):
        - γ > 0: Bad news (negative returns) increases volatility more
        - γ = 0: Standard GARCH(1,1)

    Parameters
    ----------
    sigma0 : float
        Initial volatility (annualized)
    omega : float
        Constant term in variance equation (ω > 0)
    alpha : float
        ARCH coefficient (α ≥ 0)
    beta : float
        GARCH coefficient (β ≥ 0)
    gamma : float
        Asymmetry coefficient (γ ≥ 0 for leverage effect)

    Notes
    -----
    - Stationarity requires: α + 0.5·γ + β < 1
    - Long-run variance: ω / (1 - α - 0.5·γ - β)
    - The factor 0.5 comes from E[I] = 0.5 for symmetric innovations

    Examples
    --------
    simulator = GJRGARCHSimulator(
        sigma0=0.20, omega=0.002, alpha=0.03, beta=0.90, gamma=0.07
    )
    result = simulator.simulate_paths(s0=100, mu=0.08, t=1.0, n_paths=10000, n_steps=252)
    """

    def __init__(
        self, sigma0: float, omega: float, alpha: float, beta: float, gamma: float
    ) -> None:
        super().__init__()
        self._model_name = "GJR-GARCH"
        self._sigma0 = sigma0
        self._omega = omega
        self._alpha = alpha
        self._beta = beta
        self._gamma = gamma

        self._validate_parameters()

    def _validate_parameters(self) -> None:
        """Validate GJR-GARCH parameters."""
        if self._sigma0 <= 0:
            raise ValueError(
                f"Initial volatility sigma0 must be positive, got {self._sigma0}"
            )
        if self._omega <= 0:
            raise ValueError(f"Omega must be positive, got {self._omega}")
        if self._alpha < 0:
            raise ValueError(f"Alpha must be non-negative, got {self._alpha}")
        if self._beta < 0:
            raise ValueError(f"Beta must be non-negative, got {self._beta}")
        if self._gamma < 0:
            raise ValueError(
                f"Gamma must be non-negative for leverage effect, got {self._gamma}"
            )

        persistence = self._alpha + 0.5 * self._gamma + self._beta
        if persistence >= 1:
            raise ValueError(
                f"Process is not stationary: α + 0.5γ + β = {persistence:.4f} ≥ 1. "
                f"Reduce α, β, or γ."
            )

    # Properties
    @property
    def sigma0(self) -> float:
        return self._sigma0

    @property
    def omega(self) -> float:
        return self._omega

    @property
    def alpha(self) -> float:
        return self._alpha

    @property
    def beta(self) -> float:
        return self._beta

    @property
    def gamma(self) -> float:
        return self._gamma

    @property
    def persistence(self) -> float:
        """Returns α + 0.5γ + β, the persistence of shocks."""
        return self._alpha + 0.5 * self._gamma + self._beta

    def get_parameters(self) -> dict[str, Any]:
        """Returns model parameters."""
        return {
            "sigma0": self._sigma0,
            "omega": self._omega,
            "alpha": self._alpha,
            "beta": self._beta,
            "gamma": self._gamma,
        }

    def long_run_variance(self) -> float:
        """Returns the theoretical long-run variance."""
        return self._omega / (1 - self.persistence)

    def long_run_volatility(self) -> float:
        """Returns the theoretical long-run volatility."""
        return np.sqrt(self.long_run_variance())

    def feller_condition_satisfied(self) -> bool:
        """Returns whether process is stationary."""
        return self.persistence < 1

    def news_impact_curve(self, z_range: np.ndarray) -> np.ndarray:
        """
        Compute the news impact curve (NIC).

        Shows the asymmetric response to positive vs negative shocks.

        Parameters
        ----------
        z_range : np.ndarray
            Range of standardized shocks to evaluate

        Returns
        -------
        np.ndarray
            Conditional variance values for each shock
        """
        var = self.long_run_variance()
        result = np.empty_like(z_range)

        for i, z in enumerate(z_range):
            indicator = 1.0 if z < 0 else 0.0
            result[i] = (
                self._omega
                + (self._alpha + self._gamma * indicator) * var * z**2
                + self._beta * var
            )

        return result

    def simulate_paths(
        self,
        s0: float,
        mu: float,
        t: float,
        n_paths: int,
        n_steps: int,
        seed: int | None = None,
    ) -> SimulationResult:
        """
        Simulate GJR-GARCH price and volatility paths.

        Returns
        -------
        SimulationResult
            Result with both price_paths and volatility_paths
        """
        self.validate_inputs(s0, mu, t, n_paths, n_steps)

        rng = np.random.default_rng(seed)
        z_noise = rng.standard_normal((n_paths, n_steps))

        start_time = time.perf_counter()

        price_paths, vol_paths = _simulate_gjr_garch_paths(
            s0,
            mu,
            self._sigma0,
            self._omega,
            self._alpha,
            self._beta,
            self._gamma,
            t,
            n_paths,
            n_steps,
            z_noise,
        )

        computation_time = time.perf_counter() - start_time
        time_grid = np.linspace(0, t, n_steps + 1)

        return SimulationResult(
            price_paths=price_paths,
            time_grid=time_grid,
            model_name=self._model_name,
            computation_time=computation_time,
            n_paths=n_paths,
            n_steps=n_steps,
            volatility_paths=vol_paths,
            parameters=self.get_parameters() | {"s0": s0, "mu": mu, "t": t},
        )

    def simulate_terminal(
        self,
        s0: float,
        mu: float,
        t: float,
        n_paths: int,
        n_steps: int,
        seed: int | None = None,
    ) -> np.ndarray:
        """
        Simulate only terminal prices S(T).

        Returns
        -------
        np.ndarray
            Terminal prices, shape (n_paths,)
        """
        self.validate_inputs(s0, mu, t, n_paths, n_steps)

        rng = np.random.default_rng(seed)
        z_noise = rng.standard_normal((n_paths, n_steps))

        return _simulate_gjr_garch_terminal(
            s0,
            mu,
            self._sigma0,
            self._omega,
            self._alpha,
            self._beta,
            self._gamma,
            t,
            n_paths,
            n_steps,
            z_noise,
        )


# =============================================================================
# Convenience Function
# =============================================================================


def simulate_gjr_garch(
    s0: float,
    mu: float,
    sigma0: float,
    omega: float,
    alpha: float,
    beta: float,
    gamma: float,
    t: float,
    n_paths: int = 100000,
    n_steps: int = 252,
    seed: int | None = None,
    terminal_only: bool = False,
) -> SimulationResult | np.ndarray:
    """
    Convenience function for GJR-GARCH simulation.

    Parameters
    ----------
    s0 : float
        Initial stock price
    mu : float
        Expected return (annualized)
    sigma0 : float
        Initial volatility
    omega : float
        GJR-GARCH constant term
    alpha : float
        ARCH coefficient
    beta : float
        GARCH coefficient
    gamma : float
        Asymmetry coefficient
    t : float
        Time horizon in years
    n_paths : int
        Number of paths
    n_steps : int
        Number of steps
    seed : int, optional
        Random seed
    terminal_only : bool
        Return only terminal values

    Returns
    -------
    SimulationResult or np.ndarray
    """
    simulator = GJRGARCHSimulator(
        sigma0=sigma0, omega=omega, alpha=alpha, beta=beta, gamma=gamma
    )

    if terminal_only:
        return simulator.simulate_terminal(s0, mu, t, n_paths, n_steps, seed)
    return simulator.simulate_paths(s0, mu, t, n_paths, n_steps, seed)


# =============================================================================
# Benchmark
# =============================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("GJR-GARCH Benchmark")
    print("=" * 60)

    # Test parameters
    s0, mu, t, n_steps = 100.0, 0.08, 1.0, 252
    # omega calibrated for ~20% long-run vol
    sigma0, omega, alpha, beta, gamma = 0.20, 0.002, 0.03, 0.90, 0.07

    # Warmup JIT compilation
    print("\nWarming up JIT compilation...")
    _ = simulate_gjr_garch(
        s0,
        mu,
        sigma0,
        omega,
        alpha,
        beta,
        gamma,
        t,
        n_paths=1000,
        n_steps=10,
        terminal_only=True,
    )

    # Benchmark different path counts
    path_counts = [10_000, 50_000, 100_000, 500_000]

    print(f"\n{'Paths':>12} {'Time (ms)':>12} {'Paths/sec':>15}")
    print("-" * 42)

    for n_paths in path_counts:
        start = time.perf_counter()
        result = simulate_gjr_garch(
            s0,
            mu,
            sigma0,
            omega,
            alpha,
            beta,
            gamma,
            t,
            n_paths=n_paths,
            n_steps=n_steps,
        )
        elapsed = time.perf_counter() - start

        paths_per_sec = n_paths / elapsed
        print(f"{n_paths:>12,} {elapsed * 1000:>12.2f} {paths_per_sec:>15,.0f}")

    print()
